"""initial schema (ORM)

Revision ID: 5d3f4e58a7ae
Revises: 
Create Date: 2026-08-23 09:19:05.060287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5d3f4e58a7ae'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('target', sa.JSON(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('m_demand_forecast_param',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('param_key', sa.String(length=128), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('param_key')
    )
    op.create_table('place',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('place_code', sa.String(length=32), nullable=False),
    sa.Column('place_name', sa.String(length=128), nullable=False),
    sa.Column('place_type', sa.String(length=16), nullable=False),
    sa.CheckConstraint("place_type IN ('store','warehouse')", name='place_place_type_check'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('place_code')
    )
    op.create_table('product_group',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('group_code', sa.String(length=64), nullable=False),
    sa.Column('group_name', sa.String(length=255), nullable=False),
    sa.Column('hierarchy_level', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_code')
    )
    op.create_table('sys_user',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("role IN ('buyer','inv_ctrl','exec','admin')", name='sys_user_role_check'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('product',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('sku_code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('product_group_id', sa.BigInteger(), nullable=True),
    sa.Column('mds', sa.String(length=64), nullable=True),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('supplier_code', sa.String(length=64), nullable=True),
    sa.Column('lead_time_days', sa.Numeric(precision=8, scale=2), server_default='7', nullable=True),
    sa.Column('lead_time_std', sa.Numeric(precision=8, scale=2), server_default='1', nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_group_id'], ['product_group.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku_code')
    )
    op.create_table('anomaly_alert',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('place_id', sa.BigInteger(), nullable=False),
    sa.Column('anomaly_type', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('detected_at', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='open', nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recommended_action', sa.String(length=255), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("severity IN ('low','medium','high','critical')", name='anomaly_alert_severity_check'),
    sa.CheckConstraint("status IN ('open','ack','done')", name='anomaly_alert_status_check'),
    sa.ForeignKeyConstraint(['place_id'], ['place.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_daily',
    sa.Column('inventory_date', sa.Date(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('place_id', sa.BigInteger(), nullable=False),
    sa.Column('on_hand_qty', sa.Numeric(), server_default='0', nullable=False),
    sa.Column('allocated_qty', sa.Numeric(), server_default='0', nullable=False),
    sa.Column('available_qty', sa.Numeric(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['place.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('inventory_date', 'product_id', 'place_id')
    )
    op.create_table('purchase_history',
    sa.Column('po_date', sa.Date(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('place_id', sa.BigInteger(), nullable=False),
    sa.Column('order_qty', sa.Numeric(), server_default='0', nullable=False),
    sa.Column('received_qty', sa.Numeric(), nullable=True),
    sa.Column('expected_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['place_id'], ['place.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('po_date', 'product_id', 'place_id')
    )
    op.create_table('result_abc_xyz',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('abc_class', sa.String(length=1), nullable=True),
    sa.Column('xyz_class', sa.String(length=1), nullable=True),
    sa.Column('calc_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('sales_amount', sa.Numeric(), nullable=True),
    sa.Column('cv', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("abc_class IN ('A','B','C')", name='result_abc_xyz_abc_class_check'),
    sa.CheckConstraint("xyz_class IN ('X','Y','Z')", name='result_abc_xyz_xyz_class_check'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'calc_date')
    )
    op.create_table('result_forecast',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('place_id', sa.BigInteger(), nullable=False),
    sa.Column('forecast_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('forecast_p50', sa.Numeric(), nullable=True),
    sa.Column('forecast_p80', sa.Numeric(), nullable=True),
    sa.Column('forecast_p95', sa.Numeric(), nullable=True),
    sa.Column('actual_qty', sa.Numeric(), nullable=True),
    sa.Column('model_name', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['place_id'], ['place.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'place_id', 'forecast_date', 'target_date')
    )
    op.create_table('result_order_recommendation',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('place_id', sa.BigInteger(), nullable=False),
    sa.Column('calc_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('forecast_demand', sa.Numeric(), nullable=True),
    sa.Column('safety_stock', sa.Numeric(), nullable=True),
    sa.Column('on_hand_qty', sa.Numeric(), nullable=True),
    sa.Column('recommended_qty', sa.Numeric(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("status IN ('pending','adjusted','approved','rejected')", name='result_order_recommendation_status_check'),
    sa.ForeignKeyConstraint(['place_id'], ['place.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'place_id', 'calc_date')
    )
    op.create_table('result_safety_stock',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('place_id', sa.BigInteger(), nullable=False),
    sa.Column('calc_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('safety_stock', sa.Numeric(), nullable=True),
    sa.Column('reorder_point', sa.Numeric(), nullable=True),
    sa.Column('order_qty', sa.Numeric(), nullable=True),
    sa.Column('avg_demand', sa.Numeric(), nullable=True),
    sa.Column('demand_std', sa.Numeric(), nullable=True),
    sa.Column('lead_time_days', sa.Numeric(), nullable=True),
    sa.Column('service_level', sa.Numeric(), nullable=True),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("mode IN ('pos_only','full')", name='result_safety_stock_mode_check'),
    sa.ForeignKeyConstraint(['place_id'], ['place.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'place_id', 'calc_date')
    )
    op.create_table('sku_daily_sales',
    sa.Column('sales_date', sa.Date(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('place_id', sa.BigInteger(), nullable=False),
    sa.Column('qty_sold', sa.Numeric(), server_default='0', nullable=False),
    sa.Column('amount', sa.Numeric(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['place.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('sales_date', 'product_id', 'place_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sku_daily_sales')
    op.drop_table('result_safety_stock')
    op.drop_table('result_order_recommendation')
    op.drop_table('result_forecast')
    op.drop_table('result_abc_xyz')
    op.drop_table('purchase_history')
    op.drop_table('inventory_daily')
    op.drop_table('anomaly_alert')
    op.drop_table('product')
    op.drop_table('sys_user')
    op.drop_table('product_group')
    op.drop_table('place')
    op.drop_table('m_demand_forecast_param')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
