"""add source to anomaly_alert

Revision ID: 96c24e695ffb
Revises: 5d3f4e58a7ae
Create Date: 2026-08-23 09:20:33.140393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96c24e695ffb'
down_revision: Union[str, Sequence[str], None] = '5d3f4e58a7ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anomaly_alert', sa.Column('source', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('anomaly_alert', 'source')
    # ### end Alembic commands ###
